# Generated by Django 5.1.4 on 2025-01-27 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expected arrival time')),
                ('total_passenger', models.IntegerField(default=1)),
                ('can_share', models.BooleanField(default=False, verbose_name='Shared ride')),
                ('vehicle_type', models.CharField(blank=True, default='', verbose_name='Expected vehicle type*')),
                ('sp_info', models.TextField(blank=True, default='', verbose_name='Special Needs*')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_rides', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL)),
                ('share_user', models.ManyToManyField(related_name='share_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_time', 'is_confirmed'],
            },
        ),
    ]
