# Generated by Django 5.1.4 on 2025-01-27 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ride', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ridemodel',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridemodel',
            name='share_user',
            field=models.ManyToManyField(related_name='share_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
