# Generated by Django 5.1.4 on 2025-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridemodel',
            options={'ordering': ['-pub_time', 'status']},
        ),
        migrations.RemoveField(
            model_name='ridemodel',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='ridemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('complete', 'complete')], default='pending', max_length=30),
        ),
    ]
