# Generated by Django 5.1.6 on 2025-02-05 20:15

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_ridemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('complete', 'complete')], default='pending', max_length=50, protected=True),
        ),
    ]
