version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      environment:
        DB_HOST: db
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      environment:
        DB_HOST: db
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
       - ./web-app/static:/static
     depends_on:
       - web
volumes:
   data-volume:
