name: Deploy to Production

on:
  push:
    branches: [ "main" ]  # 监听 main 分支推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/rideshare-app:latest .
          docker push your-dockerhub-username/rideshare-app:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/rideshare-app:latest
            docker stop rideshare-app || true
            docker rm rideshare-app || true
            docker run -d --name rideshare-app -p 8000:8000 your-dockerhub-username/rideshare-app:latest