name: Deploy to Production

on:
  push:
    branches: [ "master" ]  # 监听 main 分支推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/yy465/ECE-568/myRSS/RideSharingService/docker-deploy
            git pull
            docker compose up -d --no-deps --build